project_id = "ynooatjtgstgwfssnira"

[functions.download-file]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.upload-certificate-template]
verify_jwt = false

[functions.reset-certification]
verify_jwt = false

[functions.analyze-certificate-template]
verify_jwt = false
